### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by rs-2**
Add sign-in form

### CODE REVIEW

**Comment by rs-2** [comment]
Thank you for your collaboration

**Comment by rs-2** [comment]
We have no conflicts and we are ready to go 👌

**Comment by rox-streuli** [comment]
Hi, before merging add 'form' below 'natbar' to finish the pull request. Thank you.

**Review by rs-2 — COMMENTED** [review]
👍

**Comment by rs-2** [comment]
@rs-2 Something is missing.

**Pull request merged**
